import { create } from "@metaplex-foundation/mpl-core";
import {
  generateSigner,
  publicKey,
  createGenericFile,
} from "@metaplex-foundation/umi";
import { base58 } from "@metaplex-foundation/umi/serializers";
import { getUmi } from "@/lib/solana";
import { rateLimit, rateLimitResponse } from "@/lib/rateLimit";
import type { SitePlan } from "@/lib/types";

export const runtime = "nodejs";
export const maxDuration = 60;

type MintBody = {
  imageBase64?: unknown;
  planJson?: unknown;
  recipientAddress?: unknown;
  brief?: unknown;
};

function decodeImage(base64: string): Uint8Array {
  // Strip data URL prefix if present.
  const comma = base64.indexOf(",");
  const payload = comma === -1 ? base64 : base64.slice(comma + 1);
  return new Uint8Array(Buffer.from(payload, "base64"));
}

function attributesFromPlan(plan: SitePlan) {
  const acres = ((plan.lot.width * plan.lot.depth) / 43560).toFixed(2);
  const buildings = plan.buildings ?? [];
  const totalStories = buildings.reduce((sum, b) => sum + (b.stories ?? 0), 0);
  const parkingCount = plan.parking?.length ?? 0;

  return [
    { trait_type: "Lot Acres", value: acres },
    { trait_type: "Lot Width (ft)", value: String(plan.lot.width) },
    { trait_type: "Lot Depth (ft)", value: String(plan.lot.depth) },
    { trait_type: "Buildings", value: String(buildings.length) },
    { trait_type: "Total Stories", value: String(totalStories) },
    { trait_type: "Parking Spots", value: String(parkingCount) },
  ];
}

export async function POST(req: Request) {
  const limited = rateLimit(req, { bucket: "mint", limit: 5, windowMs: 60_000 });
  if (!limited.ok) return rateLimitResponse(limited);

  let body: MintBody;
  try {
    body = await req.json();
  } catch {
    return Response.json({ ok: false, error: "Body must be JSON." }, { status: 400 });
  }

  const imageBase64 = typeof body.imageBase64 === "string" ? body.imageBase64 : "";
  const recipientAddress =
    typeof body.recipientAddress === "string" ? body.recipientAddress.trim() : "";
  const brief = typeof body.brief === "string" ? body.brief : "";
  const planJson =
    body.planJson && typeof body.planJson === "object"
      ? (body.planJson as SitePlan)
      : null;

  if (!imageBase64) {
    return Response.json({ ok: false, error: "imageBase64 is required." }, { status: 400 });
  }
  if (!recipientAddress) {
    return Response.json(
      { ok: false, error: "recipientAddress is required." },
      { status: 400 }
    );
  }
  if (!planJson) {
    return Response.json({ ok: false, error: "planJson is required." }, { status: 400 });
  }

  let umi;
  try {
    umi = getUmi();
  } catch (err) {
    return Response.json(
      { ok: false, error: err instanceof Error ? err.message : "Solana init failed." },
      { status: 500 }
    );
  }

  // Validate recipient before doing anything expensive.
  let owner;
  try {
    owner = publicKey(recipientAddress);
  } catch {
    return Response.json(
      { ok: false, error: "recipientAddress is not a valid Solana public key." },
      { status: 400 }
    );
  }

  try {
    // 1. Upload the screenshot.
    const imageBytes = decodeImage(imageBase64);
    const imageFile = createGenericFile(imageBytes, "plan.png", {
      contentType: "image/png",
    });
    const [imageUri] = await umi.uploader.upload([imageFile]);

    // 2. Build + upload metadata.
    const name = `Parcel Plan #${Date.now().toString().slice(-8)}`;
    const metadata = {
      name,
      description: brief || "A site plan generated by Parcel.",
      image: imageUri,
      external_url: "https://parcel.app",
      attributes: attributesFromPlan(planJson),
      properties: {
        files: [{ uri: imageUri, type: "image/png" }],
        category: "image",
        plan_json: planJson,
      },
    };
    const metadataUri = await umi.uploader.uploadJson(metadata);

    // 3. Mint a Metaplex Core asset directly to the recipient.
    const asset = generateSigner(umi);
    const result = await create(umi, {
      asset,
      name,
      uri: metadataUri,
      owner,
    }).sendAndConfirm(umi);

    const signature = base58.deserialize(result.signature)[0];
    const mintAddress = asset.publicKey.toString();

    return Response.json({
      ok: true,
      signature,
      mintAddress,
      metadataUri,
      imageUri,
      solscanUrl: `https://solscan.io/token/${mintAddress}?cluster=devnet`,
    });
  } catch (err) {
    const detail = err instanceof Error ? err.message : String(err);
    const isFunding = /insufficient|0x1\b|lamports|balance/i.test(detail);
    return Response.json(
      {
        ok: false,
        error: isFunding
          ? "Backend wallet is out of devnet SOL. Airdrop more: solana airdrop 2 <address> --url devnet"
          : "Mint failed.",
        detail,
      },
      { status: 502 }
    );
  }
}
